#!/usr/bin/env bash

function asksure() {
echo -n "Are you sure (Y/N)? "
while read -r -n 1 -s answer; do
  if [[ $answer = [YyNn] ]]; then
    [[ $answer = [Yy] ]] && retval=0
    [[ $answer = [Nn] ]] && retval=1
    break
  fi
done
echo # just a final linefeed, optics...
return $retval
}

set -e
branch=$1
if [ "$branch" != "" ]; then
  if asksure; then 
    read -r -p "Are you sure you want to delete $branch... Press CTRL-c to cancel or Enter to continue.." -n 1 dummy
    git push origin --delete $branch
  fi   
fi 
git fetch --prune
git branch -D `git branch -vv | grep ': gone] ' | awk '{print $1}' | xargs`

